# Generated by Django 5.2 on 2025-04-13 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cadastro_cliente',
            new_name='CadastroCliente',
        ),
    ]
